### PR TITLE
TS: return Chainable type generic

### PR DESCRIPTION
**Pull request by Stumblinbear**
Updates the typescript definitions to properly set the `Chainable` return type to the return of the `commandsFn`. Contains no changes to the actual functionality of the library.

While technically possible for people that are using it to start getting TS complains following this change, that would only be if their tests are already borked. It just takes the return value from the `commandsFn` and sets it as the returned `Chainable` type, rather than the return type always being `any`.

### CODE REVIEW

**Comment by bahmutov** [comment]
@Stumblinbear this repo does typescript lint pass. Is there a spec file that this PR fixes? Can you add a spec file like that to verify the change?

**Comment by Stumblinbear** [comment]
This isn't really a "fix" just a quality of life change. Previously the Chainable would always result in an `any` output, making writing the tests a bit more painful due to lack of type checking. This properly infers the output from the `commandsFn` Chainable return value.

**Comment by Stumblinbear** [comment]
I'm not exactly sure what you wanted, but there's now a test which will throw a lint error if it's not a `number`. However, it won't throw if it's resolved to be `any` (there is no way to do that).

This also includes an additional generic in the log options, and now properly handles Promise types how they function internally

**Comment by bahmutov** [comment]
Super, this is what I wanted - specs with a few types to confirm your change

**Comment by bahmutov** [comment]
Hehehe

**Comment by bahmutov** [comment]
Trevin, would you like maintain this repo? That way you are not blocked by me

**Comment by Stumblinbear** [comment]
I don't think I have much to offer by way of ongoing maintenance, but if you like

**Comment by bahmutov** [comment]
No worries @Stumblinbear let me leave everything as is then, and I will be happy to merge the fix

**Pull request merged**
